const PROJECT_ADDRESS = "8Myc9f4fBVT3MNPobuV4CssNBBBDD5jmhzguwvArrZAY";
const RESOURCE_ADDRESS = "RF1giWg7uJ3y5Jo75TESDdwD3XWNZCL6t4jftkmkaKF";
const CHARACTER_ASSEMBLER_ADDRESS =
  "H3S7gzfi4u8GYvN4EqiaGjzGhLvacTaZvMkmfyZYYWkx";

const CHARACTER_MODEL_ADDRESS = "HiEqSXeRyVELBUvo8oMsSkipQuDqqNYbQUeqK6ivSiJN";

const MISSION_POOL_ADDRESS = "9FQCF5Hupe4kibhqvFS92XBoYQDAp32UhJbEoaLhXqa";

const MISSION_ADDRESS = "rBP8Zu2P1iA8atV4CfbnjoBLTefMXRcUDDKjtxY3BiZ";

module.exports = {
  PROJECT_ADDRESS,
  RESOURCE_ADDRESS,
  CHARACTER_MODEL_ADDRESS,
  MISSION_POOL_ADDRESS,
  MISSION_ADDRESS,
  CHARACTER_ASSEMBLER_ADDRESS,
};
